### ISSUE TITLE
tvdmss Error when no Shape Outliers are Found

### ISSUE THREAD

**Issue by creutzml** [cran/fdaoutlier#1]
Error tripped: 

`Error in functional_boxplot(dts, depth_values = tvd, emp_factor = emp_factor_tvd,  : 
  Argument 'central_region' must be greater than 0 and less than 1.`

First if statement is where I believe the error is:

```r
if (length(shape_boxstats$out) != 0) {
  shape_outliers <- which(mss %in% shape_boxstats$out[shape_boxstats$out < mean(mss)])
  dts <- dts[-shape_outliers, ]
  tvd <- tvd[-shape_outliers]
  index <- index[-shape_outliers]
}
```

The issue is that an MSS value may be outlying positively (above the median), which makes the initial `if` statement `TRUE`. But then `shape_outliers` returns `integer (empty)`. Thus, when indexing `dts` and `tvd` with `shape_outliers`, it gives back an empty data set. 

Finally, this causes an issue when calling `functional_boxplot` because now `central_region = 0`.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by creutzml** [comment]
ah, my fault! I wondered if I reported it the right place, considering it was a mirror. I'm a bit newer to GitHub still, so I appreciate the help! :)
